Use Case 2/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Home_Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Use Case 2/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Home_Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Special_Package__c</fullName>
        <label>Special Package</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Black</fullName>
                </value>
                <value>
                    <fullName>Metal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

Use Case 2/objects/Product_Information__mdt.object
<CustomObject>
    <fields>
        <fullName>ATM_Fee_in_other_currencies__c</fullName>
        <label>ATM Fee in other currencies</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <label>Card Replacement Cost</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Per_Calendar_Month__c</fullName>
        <label>Cost Per Calendar Month</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Country__c</fullName>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DE</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>UK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Special_Packages__c</fullName>
        <label>Special Packages</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Black</fullName>
                </value>
                <value>
                    <fullName>Metal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Information</label>
    <pluralLabel>Product Information</pluralLabel>
</CustomObject>

Use Case 2/globalValueSets/Home_Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Home Country</masterLabel>
</GlobalValueSet>

Use Case 2/classes/ProductInformationController.cls
/*This class is used to get product information based on the Product and Home Country selected on Contact 
 * Also the contact should be related to case id from lightning component 
*/
public class ProductInformationController {
    @AuraEnabled
    public static map<String,map<String,String>>mapCostPerCalendar{get;set;}
    @AuraEnabled
    public static map<String,map<String,String>> mapATMFees{get;set;}
    @AuraEnabled
    public static map<String,map<String,String>>mapCardReplCost{get;set;}
    @AuraEnabled
    public static Boolean nocontactAssociated{get;set;}
    @AuraEnabled
    public static Boolean noinfofound{get;set;}
    @AuraEnabled(cacheable=true) 
    public static ProductInformationController productInformation(String caseId){
        ProductInformationController classInstance= new ProductInformationController();
        mapCostPerCalendar = new map<String,map<String,String>>();
        mapATMFees = new map<String,map<String,String>>();
        mapCardReplCost= new map<String,map<String,String>>();
        nocontactAssociated=false;
        noinfofound= true;
        //get Product and Home Country from Contact using case query
        List<Case> caseList= [SELECT Id,
                                     ContactId,
                                     Contact.Home_Country__c,
                                     Contact.Product__c
                                FROM Case 
                             WHERE Id=:caseId
                             AND ContactId <> NULL 
                             AND Contact.Product__c <> NULL
                             AND Contact.Home_Country__c <> NULL
                             LIMIT 1];
        if(caseList <> NULL && !caseList.isEmpty()){
            map<String,map<String,String>> mapPackageCost= new map<String,map<String,String>>();
            //get Product details from product using data from case
            Integer productLimit =  Limits.getLimitQueryRows() - Limits.getQueryRows();
            String countryCode= caseList[0].Contact.Home_Country__c;
            Map<String,Map<String,String>> mapCountry_Package_Cost = new Map<String,Map<String,String>>();
            for(Product_Information__mdt prodCustomMetadata : [SELECT ATM_Fee_in_other_currencies__c,
                                                                      Card_Replacement_Cost__c, 
                                                                      Cost_Per_Calendar_Month__c,
                                                                      Home_Country__c,
                                                                      Special_Packages__c
                                                               FROM Product_Information__mdt]){
                    map<String,String> mapTypeandCost= new map<String,String>();
                    String ConcateString= prodCustomMetadata.Home_Country__c+'-'+prodCustomMetadata.Special_Packages__c;
                    mapTypeandCost.put('ATM Fees', prodCustomMetadata.ATM_Fee_in_other_currencies__c);
                    mapTypeandCost.put('Card Replacement', prodCustomMetadata.Card_Replacement_Cost__c);
                    mapTypeandCost.put('Cost Calendar', prodCustomMetadata.Cost_Per_Calendar_Month__c);
                    mapPackageCost.put(ConcateString,new map<String,String>(mapTypeandCost)); // i have not checked containskey in this map as there would be only one entry in the metadata related to Country and Package
            }
            if(mapPackageCost <> NULL && !mapPackageCost.isEmpty()){
                for(Product2 productObject : [SELECT Special_Package__c
                                              FROM Product2
                                              WHERE Id=:caseList[0].Contact.Product__c 
                                              AND Home_Country__c=: countryCode
                                              AND Special_Package__c <> NULL 
                                              LIMIT :productLimit]){
               noinfofound=false;
               String concateProd = countryCode +'-'+productObject.Special_Package__c;
                   if(mapPackageCost.containsKey(concateProd)){
                       map<String,String> mapType_Cost = mapPackageCost.get(concateProd);
                       String CostCalendar= mapType_Cost.get('Cost Calendar');
                       String ATMFee= mapType_Cost.get('ATM Fees');
                       String CardReplace= mapType_Cost.get('Card Replacement');
                       mapCostPerCalendar.put(productObject.Special_Package__c,
                                              new Map<String,String>{countryCode => CostCalendar});
                       mapATMFees.put(productObject.Special_Package__c,
                                              new Map<String,String>{countryCode => ATMFee});
                       mapCardReplCost.put(productObject.Special_Package__c,
                                              new Map<String,String>{countryCode => CardReplace});
                    }
                }
            }
        }
        else{
            nocontactAssociated = true;
        }
        return classInstance;
    }
}